(source "gnu" "http://elpa.gnu.org/packages/")
(source "melpa" "http://melpa.milkbox.net/packages/")
(source melpa-stable)

(depends-on "ace-window")
(depends-on "async")
(depends-on "avy")
(depends-on "csharp-mode")
(depends-on "diminish")
(depends-on "eww-lnum")
(depends-on "ivy")
(depends-on "keyfreq")
(depends-on "magit")
(depends-on "ripgrep")
(depends-on "smex")
(depends-on "swiper")
